# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy MovieConnect API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore  ./MovieConnect.API/MovieConnect.API.csproj

    - name: Build
      run: dotnet build ./MovieConnect.API/MovieConnect.API.csproj --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test ./MovieConnect.UnitTests/MovieConnect.UnitTests.csproj --configuration Release

    - name: Run Integration Tests
      run: dotnet test ./MovieConnect.IntegrationTests/MovieConnect.IntegrationTests.csproj --configuration Release

    - name: "Azure ACR login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER}}
        username: ${{ secrets.ACR_USERNAME}}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: "Build and push docker image"
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/movieconnect:${{ github.run_id }}
        file: ./MovieConnect.API/Dockerfile
